name: Test Workflow

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Test Echo
      run: |
        echo "Workflow is working!"
        echo "Commit: ${{ github.sha }}"
        echo "Branch: ${{ github.ref }}"
